language: python
cache: pip

services:
  - postgresql

python:
  - "3.7"

env:
  global:
    - PGUSER=postgres
    - PGDATABASE=postgres
    - PGPASSWORD=

  matrix:
    - TOXENV=django_tests
    - TOXENV=isort
    - TOXENV=black

install:
  - pip install tox tox-travis

script:
  - tox

jobs:
  include:
    # First stage is 'Tests' by default and populated from env matrix
    # expansion
    - stage: Docker images
      name: Test docker image build
      services:
        - docker
      install: skip
      script:
        - bash bin/release-docker-image.sh
      after_success: echo "deploying..."
      deploy:
        - provider: script
          script: bash bin/cicd.sh latest yes
          on:
            branch: master

        - provider: script
          script: bash bin/cicd.sh develop yes
          on:
            branch: develop

        - provider: script
          script: bash bin/cicd.sh $TRAVIS_TAG yes
          on:
            tags: true


after_success:
  - pip install codecov
  - codecov -e TOXENV

notifications:
  email: false
