language: python
cache: pip

services:
  - postgresql

python:
  - "3.7"

env:
  global:
    - PGUSER=postgres
    - PGDATABASE=postgres
    - PGPASSWORD=

  matrix:
    - TOXENV=django_tests
    - TOXENV=black

install:
  - pip install tox-travis

script:
  - tox

after_success:
  - pip install codecov
  - codecov -e TOXENV

notifications:
  email: false
